---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - n8n-ocirepository.yaml
  - n8n-db-helmrelease.yaml
  - n8n-helmrelease.yaml
  - n8n-httproute.yaml