---
# Docker configuration defaults
docker_edition: "ce"
docker_packages:
  - "docker-{{ docker_edition }}"
  - "docker-{{ docker_edition }}-cli"
  - "containerd.io"
  - "docker-buildx-plugin"
  - "docker-compose-plugin"

docker_users: []
docker_daemon_options: {}

# Repository configuration
docker_apt_release_channel: stable
docker_apt_arch: amd64
docker_apt_repository: "deb [arch={{ docker_apt_arch }}] https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} {{ docker_apt_release_channel }}"
docker_apt_ignore_key_error: true
docker_apt_gpg_key: https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg

# Service configuration
docker_service_state: started
docker_service_enabled: true
docker_restart_handler_state: restarted