---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - forgejo-ocirepository.yaml
  - forgejo-db-helmrelease.yaml
  - forgejo-pvc.yaml
  - forgejo-helmrelease.yaml
  - forgejo-httproute.yaml