---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - minecraft-pvc.yaml
  - minecraft-helmrepo.yaml
  - minecraft-helmrelease.yaml
  - minecraft-httproute.yaml