apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- namespace.yaml
- gateway-api/experimental-install-v1.4.0.yaml
- istio
- local-path-provisioner/local-path-provisioner.yaml

# Add more resources here as you create them
# - deployment.yaml
# - service.yaml
# - ingress.yaml